'\" t
.\"     Title: ykinfo
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: Version 1.17.3
.\"    Manual: YubiKey Personalization Tool Manual
.\"    Source: ykinfo
.\"  Language: English
.\"
.TH "YKINFO" "1" "Version 1\&.17\&.3" "ykinfo" "YubiKey Personalization Tool M"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ykinfo \- Get basic information from a YubiKey
.SH "SYNOPSIS"
.sp
\fBykinfo\fR [\fI\-s\fR] [\fI\-m\fR] [\fI\-H\fR] [\fI\-v\fR] [\fI\-t\fR] [\fI\-p\fR] [\fI\-1\fR] [\fI\-2\fR] [\fI\-q\fR] [\fI\-a\fR] [\fI\-c\fR] [\fI\-V\fR] [\fI\-h\fR]
.SH "DESCRIPTION"
.sp
Get basic information from a YubiKey\&. Can get serial number, version and current touch level\&. Can get all parameters at once or one at a time\&. If \fI\-q\fR is given only the relevant string from the YubiKey is written to screen\&.
.SH "OPTIONS"
.PP
\fB\-s\fR
.RS 4
get the serial number and output it\&.
.RE
.PP
\fB\-m\fR
.RS 4
get the serial number and output it as modhex\&.
.RE
.PP
\fB\-H\fR
.RS 4
get the serial number and output it as hex\&.
.RE
.PP
\fB\-v\fR
.RS 4
get the version and output it\&.
.RE
.PP
\fB\-t\fR
.RS 4
get the touch level and output it\&.
.RE
.PP
\fB\-p\fR
.RS 4
get the programming sequence and output it\&.
.RE
.PP
\fB\-1\fR
.RS 4
get the status of slot 1, 1 for programmed and 0 for empty\&.
.RE
.PP
\fB\-2\fR
.RS 4
get the status of slot 2, 1 for programmed and 0 for empty\&.
.RE
.PP
\fB\-a\fR
.RS 4
get all the information above\&.
.RE
.PP
\fB\-c\fR
.RS 4
get YubiKey capability information\&.
.RE
.PP
\fB\-q\fR
.RS 4
modifier, only show the relevant data from the YubiKey, no extra information\&.
.RE
.PP
\fB\-V\fR
.RS 4
print tool version and exit
.RE
.SH "EXAMPLE"
.sp
Output information from a YubiKey:
.sp
.if n \{\
.RS 4
.\}
.nf
$ ykinfo \-s \-m \-H \-v \-t \-p
serial: 1077254
serial_hex: 107006
serial_modhex: bcicch
version: 2\&.2\&.3
touch_level: 1793
programming_sequence: 1
$
.fi
.if n \{\
.RE
.\}
.SH "BUGS"
.sp
Report ykinfo bugs in the issue tracker (https://github\&.com/Yubico/yubikey\-personalization/issues)
.SH "SEE ALSO"
.sp
The ykpersonalize home page ⟨ URL: https://developers\&.yubico\&.com/yubikey\-personalization/ ⟩
.sp
YubiKeys can be obtained from Yubico ⟨ URL: http://www\&.yubico\&.com/ ⟩ \&.
